---
title: "Reading data from the web"
author: "Eileen Shea"
date: "10/19/2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse
        )
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

Load some packages.

```{r}
library(rvest)
library(httr)
```

### Scrape a table

First get the HTML

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_xml = read_html(url)
```

Get the tables from the HTML

```{r}
drug_use_xml %>%
  html_nodes(css = "table") %>% 
  .[[1]] %>% 
  html_table() %>% 
  slice(-1) %>% 
  as_tibble()
```

Learning Assessment:

```{r}
nyc_cost = read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") %>%
  html_nodes(css = "table") %>%
  .[[1]] %>%
  html_table(header = TRUE)
```

### Harry Potter

Let's get some Potter data!

```{r}
hpsaga_html = read_html("https://www.imdb.com/list/ls000630791/") 

titles = hpsaga_html %>% 
  html_nodes(css = ".lister-item-header a") %>% 
  html_text()

money = hpsaga_html %>% 
  html_nodes(css = ".text-small:nth-child(7) span:nth-child(5)") %>% 
  html_text()

hpsaga_df = tibble(
  title = titles, 
  gross_rev = money
)
``` 

Napoleon Dynamite Learning Assessment:

```{r}
napoleon_html = read_html("https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1")

review_titles = napoleon_html %>% 
  html_nodes(css = "#cm_cr-review_list .a-color-base") %>% 
  html_text()

review_stars = napoleon_html %>% 
  html_nodes(css = "#cm_cr-review_list .review-rating") %>% 
  html_text()

review_text = napoleon_html %>% 
  html_nodes(css = ".review-text") %>% 
  html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

### Using an API

Get the water data

```{r}
nyc_water = GET("https://data.cityofnewyork.us/resource/waf7-5gvc.csv") %>% 
  content("parsed")
```

As JSON

```{r}
nyc_water = GET("https://data.cityofnewyork.us/resource/waf7-5gvc.json") %>% 
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()
```

BRFSS

```{r}
brfss_smart2010 = 
  GET("https://data.cdc.gov/api/views/acme-vg9e/rows.csv?accessType=DOWNLOAD") %>% 
  content("parsed")
```

Where it gets complicated (and you need to use JSON):

```{r}
poke = GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()
```
